### ISSUE TITLE
getObjectView()

### ISSUE THREAD

**Issue by Xenon-s** [ioBroker/dev-docs#31]
The function "getObjectView" is not really well described. If one goes after the documentation [here](https://github.com/ioBroker/ioBroker/wiki/Adapter-Development-Documentation#object-fields) the syntax does not fit. 
If you go to the syntax help in VisualStudioCode, you don't get anywhere either. It says that you can enter the adapter name under "Design", if you do this, the code crashes. When I want to search the object database, the first parameter must be "system" only. If I want to search an adapter-specific view, it seems that I can also enter the adapter name.

![image](https://user-images.githubusercontent.com/65488191/167826956-6cbc3046-d896-4855-ba0a-e2ee7912b499.png)

 There is also a general listing missing, what can be used at "search" parameters,  [here](https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/io-package.json#L134-L181)

Example:
`this.getObjectView('system', 'device',
     {
       startkey: 'alexa2.0.Echo-Devices.', endkey: 'alexa2.0.Echo-Devices.\u9999'
     }, async (err, data) => {
         this.log.warn(JSON.stringify(data))
});`

**Comment by Apollon77** [comment]
Important infos are:
* list of the system views that are there always
* info on "adsapter specific views" and how to define them AND the info to not use them outside of the adapter itself
* info on this weird endkey \u9999 :-)

**Comment by Apollon77** [comment]
duplicate #10
